apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: team-1
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: team-1
  path: ./apps
  prune: true
  validation: client