apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: team-1
spec:
  interval: 10m0s
  # serviceAccountName: team-1
  sourceRef:
    kind: GitRepository
    name: team-1
    namespace: team-2
  path: ./apps/podinfo
  prune: true
  validation: client
